export const commands = [
  { id: 'thesis', label: 'Thesis', href: '#thesis' },
  { id: 'systems', label: 'Systems', href: '#systems' },
  { id: 'proof', label: 'Proof', href: '#proof' },
  { id: 'founder', label: 'Founder', href: '#founder' },
  { id: 'contact', label: 'Contact', href: '#contact' },
];

export const levels = {
  flagship: {
    label: 'Flagship / Active Systems',
    shortLabel: 'Flagship',
    summary: 'The ambitious systems where the CoreLumen field has the most pressure.',
  },
  tools: {
    label: 'Operational Tools',
    shortLabel: 'Tools',
    summary: 'Instruments that make agentic systems observable, governable, and useful.',
  },
  applications: {
    label: 'Product Applications',
    shortLabel: 'Applications',
    summary: 'Product surfaces where the field becomes usable for customers and creators.',
  },
};

export const systems = [
  {
    id: 'ainix',
    name: 'Ainix',
    level: 'flagship',
    tagline: 'An early agent-native operating system.',
    summary:
      'A hosted Rust userspace substrate for identity, capabilities, event logs, lattice storage, local agents, semantic context, brokers, daemon IPC, canvas records, and CLI-first dogfooding.',
    thesisRole: 'The substrate: where context, authority, local agents, and inspectable state start to behave like an operating system.',
    status: 'Private local system',
    maturity: 'Early-stage, most ambitious',
    currentFocus: 'Continue the hosted runtime dogfood path toward canvas and broker workflows.',
    proofLinks: [{ label: 'Local README', href: '#founder' }],
    primaryCta: null,
    secondaryCta: null,
    connections: ['zaxy', 'rava', 'eventloom', 'aiegis'],
  },
  {
    id: 'zaxy',
    name: 'Zaxy',
    level: 'flagship',
    tagline: 'Coordinator memory for agent teams.',
    summary:
      'Auditable, replayable, coordinated memory with parent missions, isolated worker sessions, cited findings, approval packets, and graph-backed retrieval.',
    thesisRole: 'The memory layer: durable context with provenance rather than flattened transcripts.',
    status: 'Active public repo',
    maturity: 'Active build',
    currentFocus: 'Make memory checkout, capture, and graph-backed retrieval reliable inside real agent work.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/zaxy' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/zaxy' },
    secondaryCta: null,
    connections: ['eventloom', 'pathlight', 'tugboat'],
  },
  {
    id: 'specora-core',
    name: 'Specora Core',
    level: 'flagship',
    tagline: 'Software that fixes its own blueprints.',
    summary:
      'A contract-driven development engine where YAML contracts compile into production apps and a self-healing sidecar traces runtime failures back to contract fixes.',
    thesisRole: 'The repair layer: systems that preserve intent in durable contracts and improve through verified change.',
    status: 'Returning to active work',
    maturity: 'Prototype with broad surface',
    currentFocus: 'Re-enter the contract repair loop and sharpen the self-healing application story.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/specora-core' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/specora-core' },
    secondaryCta: null,
    connections: ['ainix', 'zaxy', 'llmff'],
  },
  {
    id: 'pathlight',
    name: 'Pathlight',
    level: 'tools',
    tagline: 'A debugger for AI agents.',
    summary:
      'Visual traces, replay, live breakpoints, diffing, source mapping, and CI assertions for agent workflows.',
    thesisRole: 'The observability layer: agent behavior becomes inspectable instead of anecdotal.',
    status: 'Active public repo',
    maturity: 'Usable self-hosted tool',
    currentFocus: 'Keep traces, replay, breakpoints, and Eventloom visualization useful for agent debugging.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/pathlight' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/pathlight' },
    secondaryCta: { label: 'Docs/site', href: 'https://syndicalt.github.io/pathlight' },
    connections: ['zaxy', 'eventloom', 'llmff'],
  },
  {
    id: 'llmff',
    name: 'llmff',
    level: 'tools',
    tagline: 'FFmpeg-shaped pipelines for LLM workflows.',
    summary:
      'A Rust command-line and library tool for typed pipeline graphs, reproducible manifests, backend adapters, retrieval, validation, repair, and JSONL traces.',
    thesisRole: 'The pipeline layer: model work becomes composable, typed, repeatable, and traceable.',
    status: 'Active public repo',
    maturity: 'Release hardening',
    currentFocus: 'Harden the CLI, plugin surface, and release checks for reproducible inference workflows.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/llmff' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/llmff' },
    secondaryCta: null,
    connections: ['pathlight', 'provara', 'specora-core'],
  },
  {
    id: 'rava',
    name: 'Rava',
    level: 'tools',
    tagline: 'Action-native authorization for agents.',
    summary:
      'A Rust draft reference implementation for signed actions, delegated capabilities, replay checks, revocation checks, receipts, and attestations.',
    thesisRole: 'The permission layer: agent systems prove exact authority for exact actions.',
    status: 'Draft public repo',
    maturity: 'Protocol reference implementation',
    currentFocus: 'Clarify the V0 reference package and its boundaries before production security claims.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/rava' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/rava' },
    secondaryCta: null,
    connections: ['ainix', 'aiegis', 'eventloom'],
  },
  {
    id: 'aiegis',
    name: 'AIegis',
    level: 'tools',
    tagline: 'A security harness for AI agents.',
    summary:
      'Trust-labeled ingestion, hidden-content quarantine, memory poisoning checks, deterministic policy decisions, audit records, and guarded inspection tools.',
    thesisRole: 'The boundary layer: untrusted content stays separate from trusted context, memory, tools, and actions.',
    status: 'Active public repo',
    maturity: 'Test-backed security harness',
    currentFocus: 'Expand guarded inspection without weakening the trust-labeled boundary model.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/aiegis' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/aiegis' },
    secondaryCta: null,
    connections: ['rava', 'ainix', 'provara'],
  },
  {
    id: 'eventloom',
    name: 'Eventloom',
    level: 'tools',
    tagline: 'An append-only runtime for multi-agent systems.',
    summary:
      'A local-first TypeScript runtime where actors emit validated events, projections rebuild state, and runs can be replayed, visualized, and handed off.',
    thesisRole: 'The event layer: agent work becomes a durable, replayable sequence instead of a chat transcript.',
    status: 'Active public repo',
    maturity: 'Runtime prototype',
    currentFocus: 'Keep the append-only runtime useful as the audit spine for agent coordination.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/eventloom' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/eventloom' },
    secondaryCta: { label: 'Package', href: 'https://www.npmjs.com/package/@eventloom/runtime' },
    connections: ['zaxy', 'pathlight', 'rava'],
  },
  {
    id: 'tugboat',
    name: 'Tugboat',
    level: 'tools',
    tagline: 'Governed optimization for agent instructions.',
    summary:
      'A local-first sidecar for observing operational instruction files and producing evidence-backed review artifacts in proposal-only posture.',
    thesisRole: 'The governance layer: instructions, runbooks, policies, and evals become reviewable operating assets.',
    status: 'Active public repo',
    maturity: 'Packaged release with docs',
    currentFocus: 'Make the marketing site, docs, and PyPI package the adoption path for proposal-only instruction reviews.',
    proofLinks: [
      { label: 'GitHub', href: 'https://github.com/syndicalt/tugboat' },
      { label: 'Site/docs', href: 'https://syndicalt.github.io/tugboat' },
      { label: 'PyPI', href: 'https://pypi.org/project/tugboat-ai/' },
    ],
    primaryCta: { label: 'Visit site', href: 'https://syndicalt.github.io/tugboat' },
    secondaryCta: { label: 'PyPI package', href: 'https://pypi.org/project/tugboat-ai/' },
    connections: ['zaxy', 'llmff', 'pathlight'],
  },
  {
    id: 'provara',
    name: 'Provara',
    level: 'applications',
    tagline: 'An adaptive LLM gateway.',
    summary:
      'Multi-provider LLM routing, A/B testing, cost optimization, guardrails, observability, tenant controls, and spend intelligence behind an OpenAI-compatible API.',
    thesisRole: 'The customer-facing inference control plane: routing, quality, spend, and governance in one gateway.',
    status: 'Public product repo',
    maturity: 'Product application',
    currentFocus: 'Show how routing, spend, quality, and safety controls become usable product workflows.',
    proofLinks: [{ label: 'GitHub', href: 'https://github.com/syndicalt/provara' }],
    primaryCta: { label: 'View repo', href: 'https://github.com/syndicalt/provara' },
    secondaryCta: { label: 'Product site', href: 'https://www.provara.xyz' },
    connections: ['llmff', 'aiegis', 'pathlight'],
  },
  {
    id: 'divita',
    name: 'Divita',
    level: 'applications',
    tagline: 'A publishing platform for writers.',
    summary:
      'Blogging, book collation, collaborative eZines, marginalia, discovery, reading themes, subscriptions, and publishing workflows.',
    thesisRole: 'The creator-facing branch: careful software for turning long-form work into durable publications.',
    status: 'Deployed application',
    maturity: 'Product application',
    currentFocus: 'Keep the publishing branch connected to the broader thesis without crowding the infrastructure story.',
    proofLinks: [{ label: 'App', href: 'https://www.divita.app' }],
    primaryCta: { label: 'Visit app', href: 'https://www.divita.app' },
    secondaryCta: null,
    connections: ['specora-core'],
  },
];

export const events = [
  {
    id: 'ev-zaxy',
    date: 'May 31, 2026',
    systemId: 'zaxy',
    type: 'Active build',
    title: 'Zaxy moved to embedded graph-backed local memory.',
    summary: 'Current work centers on durable agent memory, checkout, provenance, and Codex-facing retrieval.',
    href: 'https://github.com/syndicalt/zaxy',
  },
  {
    id: 'ev-ainix',
    date: 'May 25, 2026',
    systemId: 'ainix',
    type: 'Dogfood path',
    title: 'Ainix has a CLI-first hosted runtime acceptance path.',
    summary: 'The local runtime exercises context import, proposed edits, approval, provenance, canvas, and broker APIs.',
    href: '#systems',
  },
  {
    id: 'ev-specora',
    date: 'Soon',
    systemId: 'specora-core',
    type: 'Returning focus',
    title: 'Specora Core is returning to active work.',
    summary: 'The contract repair loop belongs near the center of the CoreLumen thesis.',
    href: 'https://github.com/syndicalt/specora-core',
  },
  {
    id: 'ev-llmff',
    date: 'May 2026',
    systemId: 'llmff',
    type: 'Release hardening',
    title: 'llmff is being hardened as FFmpeg for inference.',
    summary: 'Typed pipeline manifests, traces, validation, and adapters make model work repeatable.',
    href: 'https://github.com/syndicalt/llmff',
  },
];
